<?php

/**
 * @file
 *
 * Contains hook implementations for the Mercury Editor Carousel module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function mercury_editor_carousel_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $behavior_settings = $paragraph->getAllBehaviorSettings();
  if ('carousel_items' == ($behavior_settings['layout_paragraphs']['region'] ?? '')) {
    $variables['attributes']['class'][] = 'splide__slide';
  }
}

/**
 * Implements hook_preprocess_layout_paragraphs_builder().
 */
function mercury_editor_carousel_preprocess_layout_paragraphs_builder(&$variables) {
  $variables['#attached']['library'][] = 'mercury_editor_carousel/layout_paragraphs_builder';
}
